/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Ctrl_Config;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author mikey
 */
public class FRMMenu extends javax.swing.JFrame implements Runnable {

    String horas, minutos, segundos, ampm;
    Calendar calendario;
    Thread h1;
    
    public FRMMenu() {
        initComponents();
        Ctrl_Config configuracion = new Ctrl_Config(this);
        h1 = new Thread(this);
        h1.start();
        lblFecha.setText(getFecha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEsquinaSuperiorIzquierda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        panelNuevaVenta = new javax.swing.JPanel();
        lblNuevaVenta = new javax.swing.JLabel();
        panelProductos = new javax.swing.JPanel();
        lblProductos = new javax.swing.JLabel();
        panelCategoria = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        panelClientes = new javax.swing.JPanel();
        lblClientes = new javax.swing.JLabel();
        panelProveedores = new javax.swing.JPanel();
        lblProveedores = new javax.swing.JLabel();
        panelUsuarios = new javax.swing.JPanel();
        lblUsuarios = new javax.swing.JLabel();
        panelConfiguracion = new javax.swing.JPanel();
        lblConfiguraciones = new javax.swing.JLabel();
        panelNuevaCompra = new javax.swing.JPanel();
        lblNuevaCompra = new javax.swing.JLabel();
        panelMedidas = new javax.swing.JPanel();
        lblMedidas = new javax.swing.JLabel();
        panelSuperior = new javax.swing.JPanel();
        lblReloj = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Nuevo_Cliente = new javax.swing.JTabbedPane();
        pnlProductos = new javax.swing.JPanel();
        panelIngresoDeProductos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrecioCompraProducto = new javax.swing.JTextField();
        txtCodigoProducto = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        txtPrecioVentaProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboCategoriaProducto = new javax.swing.JComboBox<>();
        cboMedidaProducto = new javax.swing.JComboBox<>();
        cboProveedorProducto = new javax.swing.JComboBox<>();
        btnIngresarProducto = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        panelPaginadorProductos = new javax.swing.JPanel();
        lblAtras = new javax.swing.JLabel();
        pnlClientes2 = new javax.swing.JPanel();
        panelIngresoClientes2 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtNombreCliente2 = new javax.swing.JTextField();
        txtTelefonoCliente2 = new javax.swing.JTextField();
        btnIngresarCliente2 = new javax.swing.JButton();
        btnEditarCliente2 = new javax.swing.JButton();
        btnNuevoCliente2 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtDireccionCliente2 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblClientes3 = new javax.swing.JTable();
        panelPaginadorClientes2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlProveedores = new javax.swing.JPanel();
        panelIngresoProveedores = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtRucProveedor = new javax.swing.JTextField();
        btnIngresarProveedor = new javax.swing.JButton();
        btnEditarProveedor = new javax.swing.JButton();
        btnNuevoProveedor = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtTelefonoProveedor = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDireccionProveedor = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        panelPaginadorProveedores = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        pnlUsuarios = new javax.swing.JPanel();
        panelNuevoUsuario = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtRucClientes = new javax.swing.JTextField();
        btnIngresarUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        btnNuevoUsuario = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        cboRolUsario = new javax.swing.JComboBox<>();
        cboCajaUsuario = new javax.swing.JComboBox<>();
        txtPasswordUsuario = new javax.swing.JPasswordField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        panelPaginadorUsuarios = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        pnlCategoria = new javax.swing.JPanel();
        panelNuevaCategoria = new javax.swing.JPanel();
        btnIngresarCategoria = new javax.swing.JButton();
        btnEditarCategoria = new javax.swing.JButton();
        btnNuevaCategoria = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        txtNombreCategoria = new javax.swing.JTextField();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblCategorias = new javax.swing.JTable();
        panelPaginadorCategorias = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        pnlMedidas = new javax.swing.JPanel();
        panelNuevaMedida = new javax.swing.JPanel();
        btnIngresarMedida = new javax.swing.JButton();
        btnEditarMedida = new javax.swing.JButton();
        btnNuevaMedida = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        txtMedida = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtNombreMedida = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        tblMedidas = new javax.swing.JTable();
        panelPaginadorMedidas = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        pnlNuevaVenta = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        tblNuevaVenta = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        txtProductoEnVenta = new javax.swing.JTextField();
        txtPrecioProductoEnVenta = new javax.swing.JTextField();
        txtTotalDeVenta = new javax.swing.JTextField();
        txtCantidadDelProductoEnVenta = new javax.swing.JTextField();
        txtStockDelProducto = new javax.swing.JTextField();
        txtPagarCon = new javax.swing.JTextField();
        btnGenerarVenta = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        cboCliente = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        txtTotalAPagar = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        txtCodNuevaVenta = new javax.swing.JTextField();
        txtVuelto = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        pnlVentas = new javax.swing.JPanel();
        jScrollPane15 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        panelPaginadorVentas = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        pnlCompras = new javax.swing.JPanel();
        jScrollPane16 = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        panelPaginadorCompras = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        pnl = new javax.swing.JPanel();
        panelIngresoClientes3 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        txtRucEmpresa = new javax.swing.JTextField();
        txtTelefonoEmpresa = new javax.swing.JTextField();
        btnEditarCliente3 = new javax.swing.JButton();
        jScrollPane17 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextPane();
        jLabel69 = new javax.swing.JLabel();
        txtNombreEmpresa = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        txtDireccionEmpresa = new javax.swing.JTextPane();
        jLabel65 = new javax.swing.JLabel();
        pnlNuevaCompra = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tblNuevaCompra = new javax.swing.JTable();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        txtProductoNC = new javax.swing.JTextField();
        txtPrecioProductoNC = new javax.swing.JTextField();
        txtTotalNC = new javax.swing.JTextField();
        txtCantidadDelProductoNC = new javax.swing.JTextField();
        txtStockNC = new javax.swing.JTextField();
        txtPagarConNC = new javax.swing.JTextField();
        btnGenerarCompra = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        cboProveedor = new javax.swing.JComboBox<>();
        jLabel60 = new javax.swing.JLabel();
        txtTotalAPagarNC = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        txtCodNC = new javax.swing.JTextField();
        txtVueltoNC = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEsquinaSuperiorIzquierda.setBackground(new java.awt.Color(0, 204, 204));
        panelEsquinaSuperiorIzquierda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio");
        panelEsquinaSuperiorIzquierda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 200, 40));

        getContentPane().add(panelEsquinaSuperiorIzquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 110));

        panelMenu.setBackground(new java.awt.Color(153, 153, 153));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNuevaVenta.setBackground(new java.awt.Color(0, 102, 102));

        lblNuevaVenta.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblNuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        lblNuevaVenta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Nventa.png"))); // NOI18N
        lblNuevaVenta.setText("Nueva Venta");
        lblNuevaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelNuevaVentaLayout = new javax.swing.GroupLayout(panelNuevaVenta);
        panelNuevaVenta.setLayout(panelNuevaVentaLayout);
        panelNuevaVentaLayout.setHorizontalGroup(
            panelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelNuevaVentaLayout.setVerticalGroup(
            panelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelMenu.add(panelNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 40));

        panelProductos.setBackground(new java.awt.Color(0, 102, 102));

        lblProductos.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblProductos.setForeground(new java.awt.Color(255, 255, 255));
        lblProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        lblProductos.setText("Productos");
        lblProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelMenu.add(panelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 40));

        panelCategoria.setBackground(new java.awt.Color(0, 102, 102));

        lblCategoria.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblCategoria.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        lblCategoria.setText("Categorías");
        lblCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelCategoriaLayout = new javax.swing.GroupLayout(panelCategoria);
        panelCategoria.setLayout(panelCategoriaLayout);
        panelCategoriaLayout.setHorizontalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelCategoriaLayout.setVerticalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelMenu.add(panelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 40));

        panelClientes.setBackground(new java.awt.Color(0, 102, 102));

        lblClientes.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblClientes.setForeground(new java.awt.Color(255, 255, 255));
        lblClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        lblClientes.setText("Clientes");
        lblClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelClientesLayout = new javax.swing.GroupLayout(panelClientes);
        panelClientes.setLayout(panelClientesLayout);
        panelClientesLayout.setHorizontalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelClientesLayout.setVerticalGroup(
            panelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelMenu.add(panelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 200, 40));

        panelProveedores.setBackground(new java.awt.Color(0, 102, 102));

        lblProveedores.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblProveedores.setForeground(new java.awt.Color(255, 255, 255));
        lblProveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedor.png"))); // NOI18N
        lblProveedores.setText("Proveedores");
        lblProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelProveedoresLayout = new javax.swing.GroupLayout(panelProveedores);
        panelProveedores.setLayout(panelProveedoresLayout);
        panelProveedoresLayout.setHorizontalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelProveedoresLayout.setVerticalGroup(
            panelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelMenu.add(panelProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 200, 40));

        panelUsuarios.setBackground(new java.awt.Color(0, 102, 102));

        lblUsuarios.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        lblUsuarios.setText("Usuarios");
        lblUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelUsuariosLayout = new javax.swing.GroupLayout(panelUsuarios);
        panelUsuarios.setLayout(panelUsuariosLayout);
        panelUsuariosLayout.setHorizontalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelUsuariosLayout.setVerticalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelMenu.add(panelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 200, 40));

        panelConfiguracion.setBackground(new java.awt.Color(0, 102, 102));

        lblConfiguraciones.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblConfiguraciones.setForeground(new java.awt.Color(255, 255, 255));
        lblConfiguraciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblConfiguraciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        lblConfiguraciones.setText("Configuración");
        lblConfiguraciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelConfiguracionLayout = new javax.swing.GroupLayout(panelConfiguracion);
        panelConfiguracion.setLayout(panelConfiguracionLayout);
        panelConfiguracionLayout.setHorizontalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConfiguraciones, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelConfiguracionLayout.setVerticalGroup(
            panelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblConfiguraciones, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelMenu.add(panelConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 200, 40));

        panelNuevaCompra.setBackground(new java.awt.Color(0, 102, 102));
        panelNuevaCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblNuevaCompra.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblNuevaCompra.setForeground(new java.awt.Color(255, 255, 255));
        lblNuevaCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNuevaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Carrito-de-compras.png"))); // NOI18N
        lblNuevaCompra.setText("Nueva Compra");

        javax.swing.GroupLayout panelNuevaCompraLayout = new javax.swing.GroupLayout(panelNuevaCompra);
        panelNuevaCompra.setLayout(panelNuevaCompraLayout);
        panelNuevaCompraLayout.setHorizontalGroup(
            panelNuevaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNuevaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelNuevaCompraLayout.setVerticalGroup(
            panelNuevaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNuevaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelMenu.add(panelNuevaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, 40));

        panelMedidas.setBackground(new java.awt.Color(0, 102, 102));

        lblMedidas.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        lblMedidas.setForeground(new java.awt.Color(255, 255, 255));
        lblMedidas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMedidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/detallista.png"))); // NOI18N
        lblMedidas.setText("Medidas");
        lblMedidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelMedidasLayout = new javax.swing.GroupLayout(panelMedidas);
        panelMedidas.setLayout(panelMedidasLayout);
        panelMedidasLayout.setHorizontalGroup(
            panelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMedidas, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelMedidasLayout.setVerticalGroup(
            panelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMedidas, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        panelMenu.add(panelMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, 40));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 660));

        panelSuperior.setBackground(new java.awt.Color(153, 153, 153));
        panelSuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReloj.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblReloj.setText("00:00:00 ");
        panelSuperior.add(lblReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 40));

        lblFecha.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblFecha.setText("DD/MM/YYYY");
        panelSuperior.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Punto de Venta");
        panelSuperior.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 60));

        jTextField1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        panelSuperior.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 200, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Buscar");
        panelSuperior.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 90, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        panelSuperior.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 20, 40));

        getContentPane().add(panelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1100, 110));

        Nuevo_Cliente.setBackground(new java.awt.Color(255, 255, 255));

        pnlProductos.setBackground(new java.awt.Color(255, 255, 255));
        pnlProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIngresoDeProductos.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresoDeProductos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso de Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15))); // NOI18N
        panelIngresoDeProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre:");
        panelIngresoDeProductos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 120, 55, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Precio de Venta:");
        panelIngresoDeProductos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 110, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Categoría:");
        panelIngresoDeProductos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 70, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Medida:");
        panelIngresoDeProductos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 60, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Precio de Compra:");
        panelIngresoDeProductos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 265, 120, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Código:");
        panelIngresoDeProductos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 40, 50, 30));

        txtPrecioCompraProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelIngresoDeProductos.add(txtPrecioCompraProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 275, 150, 30));

        txtCodigoProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelIngresoDeProductos.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 50, 150, 30));

        txtNombreProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelIngresoDeProductos.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 125, 150, 30));

        txtPrecioVentaProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelIngresoDeProductos.add(txtPrecioVentaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 200, 150, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Preveedor:");
        panelIngresoDeProductos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 70, 30));

        cboCategoriaProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelIngresoDeProductos.add(cboCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 490, 150, 35));

        cboMedidaProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelIngresoDeProductos.add(cboMedidaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 350, 150, 35));

        cboProveedorProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        panelIngresoDeProductos.add(cboProveedorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 420, 150, 35));

        btnIngresarProducto.setBackground(new java.awt.Color(0, 153, 255));
        btnIngresarProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIngresarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarProducto.setText("Ingresar");
        panelIngresoDeProductos.add(btnIngresarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 100, 35));

        btnEditarProducto.setBackground(new java.awt.Color(255, 255, 0));
        btnEditarProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarProducto.setText("Editar");
        panelIngresoDeProductos.add(btnEditarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 90, 35));

        btnNuevoProducto.setBackground(new java.awt.Color(51, 204, 0));
        btnNuevoProducto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProducto.setText("Nuevo");
        panelIngresoDeProductos.add(btnNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 90, 35));

        pnlProductos.add(panelIngresoDeProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 375, 600));

        tblProductos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio", "Cantidad", "Medida", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        pnlProductos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 670, 460));

        javax.swing.GroupLayout panelPaginadorProductosLayout = new javax.swing.GroupLayout(panelPaginadorProductos);
        panelPaginadorProductos.setLayout(panelPaginadorProductosLayout);
        panelPaginadorProductosLayout.setHorizontalGroup(
            panelPaginadorProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        panelPaginadorProductosLayout.setVerticalGroup(
            panelPaginadorProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlProductos.add(panelPaginadorProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 670, -1));

        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4_SV.png"))); // NOI18N
        pnlProductos.add(lblAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 630));

        Nuevo_Cliente.addTab("Ingreso de producto", pnlProductos);

        pnlClientes2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIngresoClientes2.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresoClientes2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15))); // NOI18N
        panelIngresoClientes2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Teléfono:");
        panelIngresoClientes2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 90, 30));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Dirección:");
        panelIngresoClientes2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, 30));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Nombre:");
        panelIngresoClientes2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, 30));

        txtNombreCliente2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelIngresoClientes2.add(txtNombreCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, 30));

        txtTelefonoCliente2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelIngresoClientes2.add(txtTelefonoCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, 30));

        btnIngresarCliente2.setBackground(new java.awt.Color(0, 153, 255));
        btnIngresarCliente2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIngresarCliente2.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarCliente2.setText("Ingresar");
        panelIngresoClientes2.add(btnIngresarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 90, 35));

        btnEditarCliente2.setBackground(new java.awt.Color(255, 255, 0));
        btnEditarCliente2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditarCliente2.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCliente2.setText("Editar");
        panelIngresoClientes2.add(btnEditarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 90, 35));

        btnNuevoCliente2.setBackground(new java.awt.Color(51, 204, 0));
        btnNuevoCliente2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevoCliente2.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente2.setText("Nuevo");
        panelIngresoClientes2.add(btnNuevoCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 90, 35));

        txtDireccionCliente2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtDireccionCliente2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane9.setViewportView(txtDireccionCliente2);

        panelIngresoClientes2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 190, 120));

        pnlClientes2.add(panelIngresoClientes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 375, 590));

        tblClientes3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Teléfono", "Dirección", "Estado"
            }
        ));
        jScrollPane10.setViewportView(tblClientes3);

        pnlClientes2.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 670, 460));

        javax.swing.GroupLayout panelPaginadorClientes2Layout = new javax.swing.GroupLayout(panelPaginadorClientes2);
        panelPaginadorClientes2.setLayout(panelPaginadorClientes2Layout);
        panelPaginadorClientes2Layout.setHorizontalGroup(
            panelPaginadorClientes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        panelPaginadorClientes2Layout.setVerticalGroup(
            panelPaginadorClientes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlClientes2.add(panelPaginadorClientes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 670, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4_SV.png"))); // NOI18N
        pnlClientes2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 750));

        Nuevo_Cliente.addTab("Nuevo cliente", pnlClientes2);

        pnlProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIngresoProveedores.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresoProveedores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15))); // NOI18N
        panelIngresoProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Teléfono:");
        panelIngresoProveedores.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, 30));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("RUC:");
        panelIngresoProveedores.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, 30));

        txtRucProveedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelIngresoProveedores.add(txtRucProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 150, 30));

        btnIngresarProveedor.setBackground(new java.awt.Color(0, 153, 255));
        btnIngresarProveedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIngresarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarProveedor.setText("Ingresar");
        panelIngresoProveedores.add(btnIngresarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 90, 35));

        btnEditarProveedor.setBackground(new java.awt.Color(255, 255, 0));
        btnEditarProveedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarProveedor.setText("Editar");
        panelIngresoProveedores.add(btnEditarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 90, 35));

        btnNuevoProveedor.setBackground(new java.awt.Color(51, 204, 0));
        btnNuevoProveedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevoProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProveedor.setText("Nuevo");
        panelIngresoProveedores.add(btnNuevoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 90, 35));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Nombre:");
        panelIngresoProveedores.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, 30));

        txtTelefonoProveedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelIngresoProveedores.add(txtTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 150, 30));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Dirección:");
        panelIngresoProveedores.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 110, 30));

        txtNombreProveedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelIngresoProveedores.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 150, 30));

        txtDireccionProveedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtDireccionProveedor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane4.setViewportView(txtDireccionProveedor);

        panelIngresoProveedores.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 190, 120));

        pnlProveedores.add(panelIngresoProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, 590));

        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Telefono", "Dirección", "Estado"
            }
        ));
        jScrollPane5.setViewportView(tblProveedores);

        pnlProveedores.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 670, 460));

        javax.swing.GroupLayout panelPaginadorProveedoresLayout = new javax.swing.GroupLayout(panelPaginadorProveedores);
        panelPaginadorProveedores.setLayout(panelPaginadorProveedoresLayout);
        panelPaginadorProveedoresLayout.setHorizontalGroup(
            panelPaginadorProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        panelPaginadorProveedoresLayout.setVerticalGroup(
            panelPaginadorProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlProveedores.add(panelPaginadorProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 670, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4_SV.png"))); // NOI18N
        pnlProveedores.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 630));

        Nuevo_Cliente.addTab("Nuevo proveedor", pnlProveedores);

        pnlUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNuevoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        panelNuevoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15))); // NOI18N
        panelNuevoUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Contraseña:");
        panelNuevoUsuario.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, 30));

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Rol:");
        panelNuevoUsuario.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 110, 30));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("RUC:");
        panelNuevoUsuario.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, 30));

        txtRucClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelNuevoUsuario.add(txtRucClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 150, 30));

        btnIngresarUsuario.setBackground(new java.awt.Color(0, 153, 255));
        btnIngresarUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIngresarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarUsuario.setText("Ingresar");
        panelNuevoUsuario.add(btnIngresarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 100, 35));

        btnEditarUsuario.setBackground(new java.awt.Color(255, 255, 0));
        btnEditarUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarUsuario.setText("Editar");
        panelNuevoUsuario.add(btnEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 90, 35));

        btnNuevoUsuario.setBackground(new java.awt.Color(51, 204, 0));
        btnNuevoUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoUsuario.setText("Nuevo");
        panelNuevoUsuario.add(btnNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 90, 35));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Nombre:");
        panelNuevoUsuario.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, 30));

        txtNombreUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelNuevoUsuario.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, 30));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Caja:");
        panelNuevoUsuario.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 30));

        cboRolUsario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panelNuevoUsuario.add(cboRolUsario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 150, 35));

        cboCajaUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        panelNuevoUsuario.add(cboCajaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 150, 35));

        txtPasswordUsuario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtPasswordUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPasswordUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelNuevoUsuario.add(txtPasswordUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, 30));

        pnlUsuarios.add(panelNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, 590));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Nombre", "Caja", "Rol", "Estado"
            }
        ));
        jScrollPane6.setViewportView(tblUsuarios);

        pnlUsuarios.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 670, 460));

        javax.swing.GroupLayout panelPaginadorUsuariosLayout = new javax.swing.GroupLayout(panelPaginadorUsuarios);
        panelPaginadorUsuarios.setLayout(panelPaginadorUsuariosLayout);
        panelPaginadorUsuariosLayout.setHorizontalGroup(
            panelPaginadorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        panelPaginadorUsuariosLayout.setVerticalGroup(
            panelPaginadorUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlUsuarios.add(panelPaginadorUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 670, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4_SV.png"))); // NOI18N
        pnlUsuarios.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 630));

        Nuevo_Cliente.addTab("Nuevo Usuario", pnlUsuarios);

        pnlCategoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNuevaCategoria.setBackground(new java.awt.Color(255, 255, 255));
        panelNuevaCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nueva Categoría", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15))); // NOI18N
        panelNuevaCategoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresarCategoria.setBackground(new java.awt.Color(0, 153, 255));
        btnIngresarCategoria.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIngresarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarCategoria.setText("Ingresar");
        panelNuevaCategoria.add(btnIngresarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 100, 35));

        btnEditarCategoria.setBackground(new java.awt.Color(255, 255, 0));
        btnEditarCategoria.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCategoria.setText("Editar");
        panelNuevaCategoria.add(btnEditarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 90, 35));

        btnNuevaCategoria.setBackground(new java.awt.Color(51, 204, 0));
        btnNuevaCategoria.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevaCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaCategoria.setText("Nuevo");
        panelNuevaCategoria.add(btnNuevaCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 35));

        jLabel36.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Nombre:");
        panelNuevaCategoria.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 100, 30));

        txtNombreCategoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelNuevaCategoria.add(txtNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 150, 30));

        pnlCategoria.add(panelNuevaCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, 590));

        tblCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Estado"
            }
        ));
        jScrollPane11.setViewportView(tblCategorias);

        pnlCategoria.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 670, 460));

        javax.swing.GroupLayout panelPaginadorCategoriasLayout = new javax.swing.GroupLayout(panelPaginadorCategorias);
        panelPaginadorCategorias.setLayout(panelPaginadorCategoriasLayout);
        panelPaginadorCategoriasLayout.setHorizontalGroup(
            panelPaginadorCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        panelPaginadorCategoriasLayout.setVerticalGroup(
            panelPaginadorCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlCategoria.add(panelPaginadorCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 670, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4_SV.png"))); // NOI18N
        pnlCategoria.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        Nuevo_Cliente.addTab("Nueva categoria", pnlCategoria);

        pnlMedidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNuevaMedida.setBackground(new java.awt.Color(255, 255, 255));
        panelNuevaMedida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15))); // NOI18N
        panelNuevaMedida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresarMedida.setBackground(new java.awt.Color(0, 153, 255));
        btnIngresarMedida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIngresarMedida.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarMedida.setText("Ingresar");
        panelNuevaMedida.add(btnIngresarMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 100, 35));

        btnEditarMedida.setBackground(new java.awt.Color(255, 255, 0));
        btnEditarMedida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditarMedida.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarMedida.setText("Editar");
        panelNuevaMedida.add(btnEditarMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 90, 35));

        btnNuevaMedida.setBackground(new java.awt.Color(51, 204, 0));
        btnNuevaMedida.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNuevaMedida.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaMedida.setText("Nuevo");
        panelNuevaMedida.add(btnNuevaMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 90, 35));

        jLabel37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Medida:");
        panelNuevaMedida.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 30));

        txtMedida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelNuevaMedida.add(txtMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 150, 30));

        jLabel38.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Nombre:");
        panelNuevaMedida.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, 30));

        txtNombreMedida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelNuevaMedida.add(txtNombreMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 150, 30));

        pnlMedidas.add(panelNuevaMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, 590));

        tblMedidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Medida", "Estado"
            }
        ));
        jScrollPane12.setViewportView(tblMedidas);

        pnlMedidas.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 670, 460));

        javax.swing.GroupLayout panelPaginadorMedidasLayout = new javax.swing.GroupLayout(panelPaginadorMedidas);
        panelPaginadorMedidas.setLayout(panelPaginadorMedidasLayout);
        panelPaginadorMedidasLayout.setHorizontalGroup(
            panelPaginadorMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        panelPaginadorMedidasLayout.setVerticalGroup(
            panelPaginadorMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlMedidas.add(panelPaginadorMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 670, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4_SV.png"))); // NOI18N
        pnlMedidas.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        Nuevo_Cliente.addTab("Medidas", pnlMedidas);

        pnlNuevaVenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNuevaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripcion", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane13.setViewportView(tblNuevaVenta);

        pnlNuevaVenta.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 1020, 390));

        jLabel35.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel35.setText("Precio");
        pnlNuevaVenta.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel39.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel39.setText("Producto");
        pnlNuevaVenta.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel40.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel40.setText("Cantidad");
        pnlNuevaVenta.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        jLabel41.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel41.setText("Total");
        pnlNuevaVenta.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jLabel42.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel42.setText("Stock");
        pnlNuevaVenta.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        jLabel43.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel43.setText("Código");
        pnlNuevaVenta.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        txtProductoEnVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtProductoEnVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaVenta.add(txtProductoEnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 130, 30));

        txtPrecioProductoEnVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPrecioProductoEnVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaVenta.add(txtPrecioProductoEnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, 30));

        txtTotalDeVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTotalDeVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaVenta.add(txtTotalDeVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 100, 30));

        txtCantidadDelProductoEnVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCantidadDelProductoEnVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaVenta.add(txtCantidadDelProductoEnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 80, 30));

        txtStockDelProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtStockDelProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaVenta.add(txtStockDelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 40, 30));

        txtPagarCon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPagarCon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaVenta.add(txtPagarCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 100, 30));

        btnGenerarVenta.setBackground(new java.awt.Color(255, 153, 0));
        btnGenerarVenta.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnGenerarVenta.setText("Generar Venta");
        pnlNuevaVenta.add(btnGenerarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 140, 40));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel44.setText("Cliente");
        pnlNuevaVenta.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jLabel45.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel45.setText("Pagar Con:");
        pnlNuevaVenta.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, -1, -1));

        jLabel46.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel46.setText("Vuelto:");
        pnlNuevaVenta.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, -1, -1));

        jLabel47.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel47.setText("Total a Pagar:");
        pnlNuevaVenta.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, -1, -1));

        cboCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaVenta.add(cboCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, 140, -1));

        jLabel48.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel48.setText("Pagar Con:");
        pnlNuevaVenta.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, -1, -1));

        txtTotalAPagar.setBackground(new java.awt.Color(0, 0, 0));
        txtTotalAPagar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTotalAPagar.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalAPagar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalAPagar.setText("**********");
        txtTotalAPagar.setBorder(null);
        pnlNuevaVenta.add(txtTotalAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 140, 30));

        jLabel49.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel49.setText("Pagar Con:");
        pnlNuevaVenta.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, -1, -1));

        txtCodNuevaVenta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodNuevaVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaVenta.add(txtCodNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 30));

        txtVuelto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtVuelto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaVenta.add(txtVuelto, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 100, 30));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4_SV.png"))); // NOI18N
        pnlNuevaVenta.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        Nuevo_Cliente.addTab("Nueva venta", pnlNuevaVenta);

        pnlVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Total", "Fecha"
            }
        ));
        jScrollPane15.setViewportView(tblVentas);

        pnlVentas.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1050, -1));

        javax.swing.GroupLayout panelPaginadorVentasLayout = new javax.swing.GroupLayout(panelPaginadorVentas);
        panelPaginadorVentas.setLayout(panelPaginadorVentasLayout);
        panelPaginadorVentasLayout.setHorizontalGroup(
            panelPaginadorVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        panelPaginadorVentasLayout.setVerticalGroup(
            panelPaginadorVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnlVentas.add(panelPaginadorVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 1050, 60));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4_SV.png"))); // NOI18N
        pnlVentas.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        Nuevo_Cliente.addTab("Lista ventas", pnlVentas);

        pnlCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Proveedor", "Total", "Fecha"
            }
        ));
        jScrollPane16.setViewportView(tblCompras);

        pnlCompras.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1050, -1));

        javax.swing.GroupLayout panelPaginadorComprasLayout = new javax.swing.GroupLayout(panelPaginadorCompras);
        panelPaginadorCompras.setLayout(panelPaginadorComprasLayout);
        panelPaginadorComprasLayout.setHorizontalGroup(
            panelPaginadorComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        panelPaginadorComprasLayout.setVerticalGroup(
            panelPaginadorComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        pnlCompras.add(panelPaginadorCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 1050, 60));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4_SV.png"))); // NOI18N
        pnlCompras.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        Nuevo_Cliente.addTab("Lista compras", pnlCompras);

        pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIngresoClientes3.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresoClientes3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15))); // NOI18N
        panelIngresoClientes3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel66.setText("Teléfono:");
        panelIngresoClientes3.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 90, 30));

        jLabel67.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel67.setText("Mensaje:");
        panelIngresoClientes3.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 110, 30));

        jLabel68.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel68.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel68.setText("Ruc:");
        panelIngresoClientes3.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, 30));

        txtRucEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelIngresoClientes3.add(txtRucEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 150, 30));

        txtTelefonoEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelIngresoClientes3.add(txtTelefonoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, 30));

        btnEditarCliente3.setBackground(new java.awt.Color(255, 255, 0));
        btnEditarCliente3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEditarCliente3.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarCliente3.setText("Modificar");
        panelIngresoClientes3.add(btnEditarCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 90, 35));

        txtMensaje.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtMensaje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane17.setViewportView(txtMensaje);

        panelIngresoClientes3.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 190, 70));

        jLabel69.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel69.setText("Nombre:");
        panelIngresoClientes3.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, 30));

        txtNombreEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        panelIngresoClientes3.add(txtNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 150, 30));

        jLabel70.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel70.setText("Dirección:");
        panelIngresoClientes3.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, 30));

        txtDireccionEmpresa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtDireccionEmpresa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jScrollPane18.setViewportView(txtDireccionEmpresa);

        panelIngresoClientes3.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 190, 110));

        pnl.add(panelIngresoClientes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 375, 590));

        jLabel65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4_SV.png"))); // NOI18N
        pnl.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        Nuevo_Cliente.addTab("Datos empresa", pnl);

        pnlNuevaCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNuevaCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripcion", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane14.setViewportView(tblNuevaCompra);

        pnlNuevaCompra.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 1020, 400));

        jLabel50.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel50.setText("Precio");
        pnlNuevaCompra.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel51.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel51.setText("Producto");
        pnlNuevaCompra.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel52.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel52.setText("Cantidad");
        pnlNuevaCompra.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, -1));

        jLabel53.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel53.setText("Total");
        pnlNuevaCompra.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, -1, -1));

        jLabel54.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel54.setText("Stock");
        pnlNuevaCompra.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        jLabel55.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel55.setText("Código");
        pnlNuevaCompra.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        txtProductoNC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtProductoNC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaCompra.add(txtProductoNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 130, 30));

        txtPrecioProductoNC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPrecioProductoNC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaCompra.add(txtPrecioProductoNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, 30));

        txtTotalNC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTotalNC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaCompra.add(txtTotalNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 100, 30));

        txtCantidadDelProductoNC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCantidadDelProductoNC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaCompra.add(txtCantidadDelProductoNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 80, 30));

        txtStockNC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtStockNC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaCompra.add(txtStockNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 40, 30));

        txtPagarConNC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPagarConNC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaCompra.add(txtPagarConNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 100, 30));

        btnGenerarCompra.setBackground(new java.awt.Color(255, 153, 0));
        btnGenerarCompra.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnGenerarCompra.setText("Generar Compra");
        pnlNuevaCompra.add(btnGenerarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, 170, 40));

        jLabel56.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel56.setText("Proveedor");
        pnlNuevaCompra.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        jLabel57.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel57.setText("Pagar Con:");
        pnlNuevaCompra.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, -1, -1));

        jLabel58.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel58.setText("Vuelto:");
        pnlNuevaCompra.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, -1, -1));

        jLabel59.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel59.setText("Total a Pagar:");
        pnlNuevaCompra.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, -1, -1));

        cboProveedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cboProveedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaCompra.add(cboProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 140, -1));

        jLabel60.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel60.setText("Pagar Con:");
        pnlNuevaCompra.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, -1, -1));

        txtTotalAPagarNC.setBackground(new java.awt.Color(0, 0, 0));
        txtTotalAPagarNC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtTotalAPagarNC.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalAPagarNC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalAPagarNC.setText("**********");
        txtTotalAPagarNC.setBorder(null);
        pnlNuevaCompra.add(txtTotalAPagarNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 140, 30));

        jLabel61.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel61.setText("Pagar Con:");
        pnlNuevaCompra.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, -1, -1));

        txtCodNC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtCodNC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaCompra.add(txtCodNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 100, 30));

        txtVueltoNC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtVueltoNC.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pnlNuevaCompra.add(txtVueltoNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, 100, 30));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo4_SV.png"))); // NOI18N
        pnlNuevaCompra.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 640));

        Nuevo_Cliente.addTab("Nueva Compra", pnlNuevaCompra);

        getContentPane().add(Nuevo_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 1100, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void calcularHora(){
        Calendar calendario = new GregorianCalendar();
        Date horaActual = new Date();
        
        calendario.setTime(horaActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM? "AM ":" PM";
        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY) - 12;
            horas = h > 9? "" + h:"0" + h;
        }else{
            horas = calendario.get(Calendar.HOUR_OF_DAY) > 9? "" + calendario.get(Calendar.HOUR_OF_DAY):"0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9? "" + calendario.get(Calendar.MINUTE):"0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9? "" + calendario.get(Calendar.SECOND):"0" + calendario.get(Calendar.SECOND);
    }
    
     @Override
    public void run() {
        Thread ct = Thread.currentThread();
        
         while (ct == h1) {             
             calcularHora();
             lblReloj.setText(horas + ":" + minutos + ":" + segundos + " " + ampm);
             try {
                 Thread.sleep(1000);
             } catch (InterruptedException e) {
                 
             }
         }
    }
    
    private String getFecha(){
        Date fecha = new Date();
        SimpleDateFormat formatoDeFecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatoDeFecha.format(fecha);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane Nuevo_Cliente;
    private javax.swing.JButton btnEditarCategoria;
    private javax.swing.JButton btnEditarCliente2;
    private javax.swing.JButton btnEditarCliente3;
    private javax.swing.JButton btnEditarMedida;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnEditarProveedor;
    public javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnGenerarCompra;
    private javax.swing.JButton btnGenerarVenta;
    private javax.swing.JButton btnIngresarCategoria;
    private javax.swing.JButton btnIngresarCliente2;
    private javax.swing.JButton btnIngresarMedida;
    private javax.swing.JButton btnIngresarProducto;
    private javax.swing.JButton btnIngresarProveedor;
    public javax.swing.JButton btnIngresarUsuario;
    private javax.swing.JButton btnNuevaCategoria;
    private javax.swing.JButton btnNuevaMedida;
    private javax.swing.JButton btnNuevoCliente2;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnNuevoProveedor;
    public javax.swing.JButton btnNuevoUsuario;
    public javax.swing.JComboBox<String> cboCajaUsuario;
    private javax.swing.JComboBox<String> cboCategoriaProducto;
    private javax.swing.JComboBox<String> cboCliente;
    private javax.swing.JComboBox<String> cboMedidaProducto;
    private javax.swing.JComboBox<String> cboProveedor;
    private javax.swing.JComboBox<String> cboProveedorProducto;
    public javax.swing.JComboBox<String> cboRolUsario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAtras;
    public javax.swing.JLabel lblCategoria;
    public javax.swing.JLabel lblClientes;
    public javax.swing.JLabel lblConfiguraciones;
    private javax.swing.JLabel lblFecha;
    public javax.swing.JLabel lblMedidas;
    public javax.swing.JLabel lblNuevaCompra;
    public javax.swing.JLabel lblNuevaVenta;
    public javax.swing.JLabel lblProductos;
    public javax.swing.JLabel lblProveedores;
    private javax.swing.JLabel lblReloj;
    public javax.swing.JLabel lblUsuarios;
    public javax.swing.JPanel panelCategoria;
    public javax.swing.JPanel panelClientes;
    public javax.swing.JPanel panelConfiguracion;
    private javax.swing.JPanel panelEsquinaSuperiorIzquierda;
    private javax.swing.JPanel panelIngresoClientes2;
    private javax.swing.JPanel panelIngresoClientes3;
    private javax.swing.JPanel panelIngresoDeProductos;
    private javax.swing.JPanel panelIngresoProveedores;
    public javax.swing.JPanel panelMedidas;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelNuevaCategoria;
    public javax.swing.JPanel panelNuevaCompra;
    private javax.swing.JPanel panelNuevaMedida;
    public javax.swing.JPanel panelNuevaVenta;
    private javax.swing.JPanel panelNuevoUsuario;
    private javax.swing.JPanel panelPaginadorCategorias;
    private javax.swing.JPanel panelPaginadorClientes2;
    private javax.swing.JPanel panelPaginadorCompras;
    private javax.swing.JPanel panelPaginadorMedidas;
    private javax.swing.JPanel panelPaginadorProductos;
    private javax.swing.JPanel panelPaginadorProveedores;
    private javax.swing.JPanel panelPaginadorUsuarios;
    private javax.swing.JPanel panelPaginadorVentas;
    public javax.swing.JPanel panelProductos;
    public javax.swing.JPanel panelProveedores;
    private javax.swing.JPanel panelSuperior;
    public javax.swing.JPanel panelUsuarios;
    private javax.swing.JPanel pnl;
    private javax.swing.JPanel pnlCategoria;
    private javax.swing.JPanel pnlClientes2;
    private javax.swing.JPanel pnlCompras;
    private javax.swing.JPanel pnlMedidas;
    private javax.swing.JPanel pnlNuevaCompra;
    private javax.swing.JPanel pnlNuevaVenta;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JPanel pnlProveedores;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JPanel pnlVentas;
    private javax.swing.JTable tblCategorias;
    private javax.swing.JTable tblClientes3;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTable tblMedidas;
    private javax.swing.JTable tblNuevaCompra;
    private javax.swing.JTable tblNuevaVenta;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTable tblVentas;
    private javax.swing.JTextField txtCantidadDelProductoEnVenta;
    private javax.swing.JTextField txtCantidadDelProductoNC;
    private javax.swing.JTextField txtCodNC;
    private javax.swing.JTextField txtCodNuevaVenta;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextPane txtDireccionCliente2;
    private javax.swing.JTextPane txtDireccionEmpresa;
    private javax.swing.JTextPane txtDireccionProveedor;
    private javax.swing.JTextField txtMedida;
    private javax.swing.JTextPane txtMensaje;
    private javax.swing.JTextField txtNombreCategoria;
    private javax.swing.JTextField txtNombreCliente2;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtNombreMedida;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtNombreProveedor;
    public javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtPagarCon;
    private javax.swing.JTextField txtPagarConNC;
    public javax.swing.JPasswordField txtPasswordUsuario;
    private javax.swing.JTextField txtPrecioCompraProducto;
    private javax.swing.JTextField txtPrecioProductoEnVenta;
    private javax.swing.JTextField txtPrecioProductoNC;
    private javax.swing.JTextField txtPrecioVentaProducto;
    private javax.swing.JTextField txtProductoEnVenta;
    private javax.swing.JTextField txtProductoNC;
    public javax.swing.JTextField txtRucClientes;
    private javax.swing.JTextField txtRucEmpresa;
    private javax.swing.JTextField txtRucProveedor;
    private javax.swing.JTextField txtStockDelProducto;
    private javax.swing.JTextField txtStockNC;
    private javax.swing.JTextField txtTelefonoCliente2;
    private javax.swing.JTextField txtTelefonoEmpresa;
    private javax.swing.JTextField txtTelefonoProveedor;
    private javax.swing.JTextField txtTotalAPagar;
    private javax.swing.JTextField txtTotalAPagarNC;
    private javax.swing.JTextField txtTotalDeVenta;
    private javax.swing.JTextField txtTotalNC;
    private javax.swing.JTextField txtVuelto;
    private javax.swing.JTextField txtVueltoNC;
    // End of variables declaration//GEN-END:variables
}
